version: 2.1

orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to NPM
          command: yarn publish --access public --non-interactive
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Lint
          command: yarn run lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Tests
          command: yarn run test

workflows:
  version: 2
  build_test_publish:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - publish:
          context: NPM_Publish
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
